-- MySQL Script generated by MySQL Workbench
-- Tue Jun 25 13:45:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mediares1.1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mediares1.1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mediares1.1` DEFAULT CHARACTER SET utf8 ;
USE `mediares1.1` ;

-- -----------------------------------------------------
-- Table `mediares1.1`.`tb_semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediares1.1`.`tb_semestre` (
  `sem_codigo` INT UNSIGNED NOT NULL,
  `sem_descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sem_codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediares1.1`.`tb_professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediares1.1`.`tb_professores` (
  `prf_codigo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `prf_nome` VARCHAR(45) NOT NULL,
  `prf_RA` VARCHAR(45) NOT NULL,
  `prf_cursoUTFPR` VARCHAR(45) NOT NULL,
  `prf_telefone` VARCHAR(45) NOT NULL,
  `prf_endereco` VARCHAR(45) NOT NULL,
  `prf_semestre` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`prf_codigo`),
  CONSTRAINT `fk_professor_semestre`
    FOREIGN KEY (`prf_semestre`)
    REFERENCES `mediares1.1`.`tb_semestre` (`sem_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediares1.1`.`tb_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediares1.1`.`tb_cursos` (
  `crs_codigo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `crs_nome` VARCHAR(45) NOT NULL,
  `crs_descricao` VARCHAR(45) NOT NULL,
  `crs_carga_horario` VARCHAR(45) NOT NULL,
  `crs_horarios` VARCHAR(45) NOT NULL,
  `tb_cursoscol` VARCHAR(45) NULL,
  PRIMARY KEY (`crs_codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediares1.1`.`tb_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediares1.1`.`tb_turma` (
  `trm_codigo` INT UNSIGNED NOT NULL,
  `trm_descricao` VARCHAR(45) NOT NULL,
  `trm_curso` INT UNSIGNED NOT NULL,
  `trm_semestre` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`trm_codigo`), 
  CONSTRAINT `fk_turma_curso`
    FOREIGN KEY (`trm_curso`)
    REFERENCES `mediares1.1`.`tb_cursos` (`crs_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_semestre`
    FOREIGN KEY (`trm_semestre`)
    REFERENCES `mediares1.1`.`tb_semestre` (`sem_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediares1.1`.`tb_alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediares1.1`.`tb_alunos` (
  `alu_codigo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `alu_nome` VARCHAR(45) NOT NULL,
  `alu_idade` VARCHAR(45) NOT NULL,
  `alu_nomeResponsavel` VARCHAR(45) NOT NULL,
  `alu_endereco` VARCHAR(45) NOT NULL,
  `alu_telefone` VARCHAR(45) NOT NULL,
  `alu_rg` VARCHAR(45) NOT NULL,
  `alu_turma` INT UNSIGNED NOT NULL,
  `alu_semestre` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`alu_codigo`),
  CONSTRAINT `fk_aluno_turma`
    FOREIGN KEY (`alu_turma`)
    REFERENCES `mediares1.1`.`tb_turma` (`trm_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_semstre`
    FOREIGN KEY (`alu_semestre`)
    REFERENCES `mediares1.1`.`tb_semestre` (`sem_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
